# Generated by Django 4.0 on 2021-12-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eemployee_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
            ],
            options={
                'db_table': 'employees',
            },
        ),
    ]
